Document: filebench
Title: Debian filebench Manual
Author: <insert document author here>
Abstract: This manual describes what filebench is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/filebench/filebench.sgml.gz

Format: postscript
Files: /usr/share/doc/filebench/filebench.ps.gz

Format: text
Files: /usr/share/doc/filebench/filebench.text.gz

Format: HTML
Index: /usr/share/doc/filebench/html/index.html
Files: /usr/share/doc/filebench/html/*.html
